import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
	],
	format: 'cjs',
	target: 'es2021',
	define: { global: 'globalThis' },
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

const wordRuntimeContext = await esbuild.context({
	entryPoints: ['src/platform/word-export-runtime.ts'],
	bundle: true,
	format: 'cjs',
	platform: 'node',
	conditions: ['node'],
	target: 'es2021',
	define: { global: 'globalThis' },
	logLevel: 'info',
	outfile: 'word-export-runtime.cjs',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await wordRuntimeContext.rebuild();
	process.exit(0);
} else {
	await context.watch();
	await wordRuntimeContext.watch();
}
